# Generated by Django 3.1.7 on 2021-04-23 10:41

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='accounts/img'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=8),
        ),
    ]
