# Generated by Django 3.1.7 on 2021-04-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210330_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='accounts/img/default.png', upload_to='accounts/img'),
        ),
    ]
