# Generated by Django 3.1.7 on 2021-04-27 14:44

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210424_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='accounts/img'),
        ),
    ]
