# Generated by Django 3.1.7 on 2021-06-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20210429_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('intern', 'インターン生'), ('engineer', 'エンジニア'), ('designer', 'デザイナー'), ('super_engineer', '凄いエンジニア'), ('awesome_designer', '素晴らしいデザイナー'), ('manager', '運営')], default='intern', max_length=16),
        ),
    ]
