# Generated by Django 3.1.7 on 2021-06-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210608_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('インターン生', 'インターン生'), ('エンジニア', 'エンジニア'), ('デザイナー', 'デザイナー'), ('凄いエンジニア', '凄いエンジニア'), ('素晴らしいデザイナー', '素晴らしいデザイナー'), ('素晴らしいデザイナー', '素晴らしいデザイナー')], default='intern', max_length=16),
        ),
    ]
