# Generated by Django 3.1.7 on 2021-04-09 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', markdownx.models.MarkdownxField()),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('msg_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_form', to=settings.AUTH_USER_MODEL)),
                ('msg_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('f_number', models.PositiveSmallIntegerField(default=0)),
                ('clear', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('contents', models.TextField(max_length=1000, null=True)),
                ('s_number', models.PositiveSmallIntegerField(default=0)),
                ('clear', models.BooleanField(default=False)),
                ('task_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sub', to='def_i.task')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', markdownx.models.MarkdownxField()),
                ('if_answered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to=settings.AUTH_USER_MODEL)),
                ('question_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_question', to='def_i.task_sub')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(null=True)),
                ('relate_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_memo', to='def_i.task_sub')),
                ('relate_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_memo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='def_i.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_article', to='def_i.task_sub'),
        ),
        migrations.AddField(
            model_name='article',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='TalkAtQuestion',
            fields=[
                ('talk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='def_i.talk')),
                ('category', models.CharField(choices=[('記事', '記事'), ('質問', '質問')], default='質問', max_length=10)),
                ('msg_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='def_i.question')),
            ],
            bases=('def_i.talk',),
        ),
        migrations.CreateModel(
            name='TalkAtArticle',
            fields=[
                ('talk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='def_i.talk')),
                ('category', models.CharField(choices=[('記事', '記事'), ('質問', '質問')], default='記事', max_length=10)),
                ('msg_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='def_i.article')),
            ],
            bases=('def_i.talk',),
        ),
    ]
