# Generated by Django 3.1.7 on 2021-04-24 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('def_i', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearedLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_lesson', to='def_i.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleared_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
