# Generated by Django 3.1.7 on 2021-03-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0002_auto_20210322_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='msg',
            field=models.TextField(max_length=1000),
        ),
    ]
