# Generated by Django 3.1.7 on 2021-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0004_auto_20210425_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_clear',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='clear',
        ),
        migrations.AddField(
            model_name='article',
            name='article_image_1',
            field=models.ImageField(null=True, upload_to='def_i/img'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_image_2',
            field=models.ImageField(null=True, upload_to='def_i/img'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
