# Generated by Django 3.1.7 on 2021-03-29 15:37

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0004_auto_20210326_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(default='default'),
            preserve_default=False,
        ),
    ]
