# Generated by Django 3.1.7 on 2021-04-02 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0005_auto_20210330_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='first_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='second_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(null=True)),
                ('relate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_memo', to='def_i.task')),
            ],
        ),
    ]
