# Generated by Django 3.1.7 on 2021-05-02 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('def_i', '0005_auto_20210427_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=100)),
                ('is_intern', models.BooleanField(default=True)),
                ('is_answerer', models.BooleanField(default=False)),
                ('notify_good', models.BooleanField(default=False)),
                ('notify_comment', models.BooleanField(default=True)),
                ('notify_answer', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
