# Generated by Django 3.1.7 on 2021-05-02 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('def_i', '0006_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.CharField(choices=[('BACKEND', 'バックエンド'), ('FRONTEND', 'フロントエンド')], default='BACKEND', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_article', to='def_i.lesson'),
        ),
        migrations.AlterField(
            model_name='article',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='def_i.course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_question', to='def_i.lesson'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='msg_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='talk',
            name='msg_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
