# Generated by Django 3.1.7 on 2021-04-03 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0006_auto_20210403_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='first_id',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='task',
            name='second_id',
        ),
        migrations.CreateModel(
            name='Task_Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('number', models.PositiveSmallIntegerField(default=0)),
                ('clear', models.BooleanField(default=False)),
                ('task_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sub', to='def_i.task')),
            ],
        ),
    ]
