# Generated by Django 3.1.7 on 2021-05-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0006_bookmark'),
        ('def_i', '0007_auto_20210502_1430'),
    ]

    operations = [
    ]
