# Generated by Django 3.1.7 on 2021-04-03 03:59

import def_i.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0007_auto_20210403_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_at',
            field=models.ForeignKey(default=def_i.models.get_task, on_delete=django.db.models.deletion.CASCADE, related_name='task_article', to='def_i.task_sub'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_at',
            field=models.ForeignKey(default=def_i.models.get_task, on_delete=django.db.models.deletion.CASCADE, related_name='task_question', to='def_i.task_sub'),
        ),
    ]
