# Generated by Django 3.1.7 on 2021-04-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0008_auto_20210403_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contents',
        ),
        migrations.AddField(
            model_name='task_sub',
            name='contents',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
