# Generated by Django 3.1.7 on 2021-05-02 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('def_i', '0008_auto_20210502_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_category', models.CharField(choices=[('BACKEND', 'バックエンド'), ('FRONTEND', 'フロントエンド')], default='BACKEND', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studying_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudyingCourse',
        ),
    ]
