# Generated by Django 3.1.7 on 2021-04-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0008_auto_20210403_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_sub',
            name='task_belong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_sub', to='def_i.task'),
        ),
    ]
