# Generated by Django 3.1.7 on 2021-04-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0009_auto_20210404_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='number',
            new_name='f_number',
        ),
        migrations.RenameField(
            model_name='task_sub',
            old_name='number',
            new_name='s_number',
        ),
    ]
