# Generated by Django 3.1.7 on 2021-05-03 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('def_i', '0009_auto_20210502_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_category',
            field=models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend'), ('design', 'design')], default='backend', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='def_i.course'),
        ),
        migrations.AlterField(
            model_name='studyingcategory',
            name='course_category',
            field=models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend'), ('design', 'design')], default='BACKEND', max_length=10),
        ),
        migrations.AlterField(
            model_name='studyingcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studying_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='talk',
            name='msg_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
