# Generated by Django 3.1.7 on 2021-05-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0009_auto_20210502_1559'),
        ('def_i', '0008_merge_20210502_1532'),
    ]

    operations = [
    ]
