# Generated by Django 3.1.7 on 2021-04-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0009_auto_20210406_1811'),
        ('def_i', '0010_auto_20210405_1558'),
    ]

    operations = [
    ]
