# Generated by Django 3.1.7 on 2021-04-08 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0011_merge_20210408_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='category',
            field=models.CharField(choices=[('記事', '記事'), ('質問', '質問')], default='記事', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memo',
            name='relate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_memo', to='def_i.task_sub'),
        ),
        migrations.AlterField(
            model_name='task_sub',
            name='task_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sub', to='def_i.task'),
        ),
    ]
