# Generated by Django 3.1.7 on 2021-04-08 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('def_i', '0011_merge_20210408_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='relate',
        ),
        migrations.AddField(
            model_name='memo',
            name='relate_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_memo', to='def_i.task_sub'),
        ),
        migrations.AddField(
            model_name='memo',
            name='relate_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_memo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task_sub',
            name='task_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sub', to='def_i.task'),
        ),
    ]
