# Generated by Django 3.1.7 on 2021-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0012_merge_20210506_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linefriend',
            name='is_intern',
            field=models.BooleanField(default=False),
        ),
    ]
