# Generated by Django 3.1.7 on 2021-04-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0012_auto_20210408_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='category',
        ),
        migrations.AddField(
            model_name='talkatarticle',
            name='category',
            field=models.CharField(choices=[('記事', '記事'), ('質問', '質問')], default='記事', max_length=10),
        ),
        migrations.AddField(
            model_name='talkatquestion',
            name='category',
            field=models.CharField(choices=[('記事', '記事'), ('質問', '質問')], default='質問', max_length=10),
        ),
    ]
