# Generated by Django 3.1.7 on 2021-05-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0013_auto_20210507_0158'),
        ('def_i', '0011_auto_20210507_1447'),
    ]

    operations = [
    ]
