# Generated by Django 3.1.7 on 2021-04-09 07:32

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0013_auto_20210408_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
