# Generated by Django 3.1.7 on 2021-05-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0014_merge_20210507_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linefriend',
            name='notify_good',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='def_i/img'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='def_i/img'),
        ),
    ]
