# Generated by Django 3.1.7 on 2021-04-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0014_auto_20210409_1632'),
        ('def_i', '0012_auto_20210408_1424'),
    ]

    operations = [
    ]
