# Generated by Django 3.1.7 on 2021-05-08 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0015_auto_20210507_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_at',
            new_name='lesson',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_question', to='def_i.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_question', to='def_i.course'),
        ),
    ]
