# Generated by Django 3.1.7 on 2021-05-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0016_auto_20210508_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='def_i/img'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='def_i/img'),
        ),
    ]
