# Generated by Django 3.1.7 on 2021-05-08 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0017_auto_20210508_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_at',
            new_name='lesson',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_article', to='def_i.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_article', to='def_i.course'),
        ),
    ]
