# Generated by Django 3.1.7 on 2021-05-12 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0019_question_bookmark_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='if_answered',
            new_name='is_answered',
        ),
    ]
