# Generated by Django 3.1.7 on 2021-06-12 08:30

import django.core.validators
from django.db import migrations
import markdownx.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0024_article_for_lesson_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image_1',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='def_i/img', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image_2',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='def_i/img', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='contents',
            field=markdownx.models.MarkdownxField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=markdownx.models.MarkdownxField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image_1',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='def_i/img', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image_2',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='def_i/img', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
