# Generated by Django 3.1.7 on 2021-06-16 19:25

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0025_auto_20210612_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='msg',
            field=markdownx.models.MarkdownxField(max_length=1000),
        ),
    ]
