# Generated by Django 3.1.7 on 2021-06-25 16:59

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0027_auto_20210617_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image_1',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='def_i/img', validators=[stdimage.validators.MaxSizeValidator(2048, 2048)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image_2',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='def_i/img', validators=[stdimage.validators.MaxSizeValidator(2048, 2048)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image_1',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='def_i/img', validators=[stdimage.validators.MaxSizeValidator(2048, 2048)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image_2',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='def_i/img', validators=[stdimage.validators.MaxSizeValidator(2048, 2048)]),
        ),
    ]
