# Generated by Django 3.1.7 on 2021-06-25 17:25

import django.core.validators
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0028_auto_20210626_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image_1',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='def_i/img', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image_2',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='def_i/img', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image_1',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='def_i/img', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image_2',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='def_i/img', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
