# Generated by Django 3.1.7 on 2021-10-13 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('def_i', '0029_auto_20210626_0225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'permissions': [('View_Lessons', 'Can view def-init lesson')]},
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
