# Generated by Django 3.1.7 on 2021-10-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0030_auto_20211013_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
    ]
