# Generated by Django 3.1.7 on 2021-11-03 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('def_i', '0031_auto_20211013_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearedlesson',
            name='cleared_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 7, 39, 37, 663067, tzinfo=utc)),
        ),
    ]
